### ISSUE TITLE
Issues when trying to load the package

### ISSUE THREAD

**Issue by fbottazzoli** [careerjet/careerjet-api-client-python#5]
I'm trying to run the example code, but I cannot even load the library: from careerjet_api_client import CareerjetAPIClient

Errore message:

Traceback (most recent call last):

  File "C:\Users\botti\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-13-32b82723b3d6>", line 1, in <module>
    from careerjet_api_client import CareerjetAPIClient

  File "C:\Users\botti\anaconda3\lib\site-packages\careerjet_api_client\__init__.py", line 114
    except Exception, e:
                    ^
SyntaxError: invalid syntax

**Comment by simplesapien** [comment]
Lol just had the same, go into the __init__ file that it points to in the error message and change the lines 114 and 122 at the bottom from "except Exception, e:" to "except Exception **as** e:"

Also change line 8 to "from urllib.parse import urlparse"
and line 106 to "referer_uri = urlparse(search_params.pop('url'))"

Worked for me.
